
dataset: [mpi3d]
vae: 
  exp_params:
    kld_weight: [16.0]
  model_params:
    latent_dim: [10]
    
model_type: [vae]

probe:
  rff_sigma_scale: ['const']
  hidden_dim: [16, 32, 64, 128, 256, 512, 1024 8192, 16384, 32768, 65536, 131072]
  rff_sigma_gain: [0.08]
  hidden_layers: [0]
  lr: [0.00002]

